name: Check the latest version
on:
  push:
    paths:
      - "**.sh"
jobs:
  build:
    name: Test the script
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v2
      - name: Test the script
        run: |
          sudo wireguard-manager.sh --install
