name: Check the latest version
on:
  push:
    paths:
      - "**.sh"
jobs:
  build:
    name: Test the script
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v2
      - name: Test the script
        run: |
          curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/main/wireguard-manager.sh --create-dirs -o /usr/local/bin/wireguard-manager.sh
          chmod +x /usr/local/bin/wireguard-manager.sh
          /usr/local/bin/wireguard-manager.sh --install
