name: Build the latest version
on:
  push:
    paths:
      - "**.sh"
jobs:
  build:
    name: Build on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v2
      - name: Install wireguard via wireguard-manager
        run: sudo ./wireguard-manager.sh --install
      - name: Start wireguard service
        run: sudo ./wireguard-manager.sh --start
      - name: Stop WireGuard service
        run: sudo ./wireguard-manager.sh --stop
      - name: Restart WireGuard service
        run: sudo ./wireguard-manager.sh --restart
      - name: Add a new WireGuard peer
        run: sudo echo -e "\n" | ./wireguard-manager.sh --add
      - name: Update wireguard-manager.
        run: sudo ./wireguard-manager.sh --update
      - name: Test wireguard-manager ddns.
        run: sudo ./wireguard-manager.sh --ddns
      - name: Test wireguard-manager backup.
        run: sudo ./wireguard-manager.sh --backup
      - name: Test wireguard-manager restore.
        run: sudo ./wireguard-manager.sh --restore
      - name: Test wireguard-manager purge.
        run: sudo ./wireguard-manager.sh --purge
      - name: View WireGuard configuration.
        run: sudo cat /etc/wireguard/wg0.conf
      - name: View unbound status.
        run: sudo systemctl status unbound
      - name: View Unbound configuration.
        run: sudo cat /etc/unbound/unbound.conf
